Location Class Reference
Represents the geographic location of an object in the simulator.
#include <location.hpp>
Public Types
typedef boost::shared_ptr< Location > LocationPtr
Smart pointer that clients should use.
Public Member Functions
Location ()
A constructor All coordinates are set to 0.0.
Location (float x, float y, float z)
A constructor.
void setCoordinates (float x, float y, float z)
Reset the coordinates.
float getX () const
Get the x coordinate.
float getY () const
Get the y coordinate.
float getZ () const
Get the z coordinate.
Static Public Member Functions
static float distance (const Location &loc1, const Location &loc2)
Get the distance in meters between two locations.
Detailed Description
Represents the geographic location of an object in the simulator.
Definition at line 14 of file location.hpp.
Constructor & Destructor Documentation
Location::Location (float x, float y, float z)
A constructor.
Parameters:
x x coordinate in meters.
y y coordinate in meters
z z coordinate in meters
Definition at line 10 of file location.cpp.
Member Function Documentation
float Location::distance (const Location & loc1, const Location & loc2) [inline, static]
Get the distance in meters between two locations.
Parameters:
loc1 one of the locations.
loc2 the other location.
Returns: the Euclidean distance in meters between the two locations.
Definition at line 90 of file location.hpp.
References getX(), getY(), and getZ().
Referenced by TwoRay::getRecvdStrength(), FreeSpace::getRecvdStrength(), and Channel::propagationDelay().
float Location::getX () const [inline]
Get the x coordinate.
Returns: the x coordinate in meters.
Definition at line 105 of file location.hpp.
Referenced by distance().
float Location::getY () const [inline]
Get the y coordinate.
Returns: the y coordinate in meters.
Definition at line 110 of file location.hpp.
Referenced by distance().
float Location::getZ () const [inline]
Get the z coordinate.
Returns: the z coordinate in meters.
Definition at line 115 of file location.hpp.
Referenced by distance().
void Location::setCoordinates (float x, float y, float z) [inline]
Reset the coordinates.
Parameters:
x the new x coordinate in meters.
y the new y coordinate in meters.
z the new z coordinate in meters.
Definition at line 98 of file location.hpp.
The documentation for this class was generated from the following files:
location.hpp
location.cpp