Ricean Class Reference
The Ricean fading model.
#include <fading.hpp>
Public Types
typedef boost::shared_ptr< Ricean > RiceanPtr
Smart pointer that clients should use.
Public Member Functions
virtual double fadingFactor (const WirelessCommSignal &signal, const NodeId &nodeId)
Compute the fading factor for the signal.
Static Public Member Functions
static RiceanPtr create ()
A factory method to ensure that all objects are created via new since we are using smart pointers.
static RiceanPtr create (const Ricean &rhs)
A factory method to ensure that all objects are created via new since we are using smart pointers.
static RiceanPtr create (double maxVelocity, double k)
A factory method to ensure that all objects are created via new since we are using smart pointers.
Protected Member Functions
Ricean ()
A constructor.
Ricean (double maxVelocity, double k)
A constructor.
Ricean (const Ricean &rhs)
A copy constructor.
Static Protected Attributes
static const double m_DEFAULT_MAX_VELOCITY = 6.5
The default maximum velocity of objects in the environment.
Detailed Description
The Ricean fading model.
This is based on the ns-2 implementation from the paper Efficient Simulation of Ricean Fading within a Packet Simulator by Punnoose et al. See the paper for details about the model.
Definition at line 64 of file fading.hpp.
Constructor & Destructor Documentation
Ricean::Ricean (double maxVelocity, double k) [protected]
A constructor.
Parameters:
maxVelocity the maximum velocity for objects in the environment in m/s (used for computing doppler).
k a Ricean parameter.
Definition at line 35 of file fading.cpp.
Member Function Documentation
RiceanPtr Ricean::create (double maxVelocity, double k) [inline, static]
A factory method to ensure that all objects are created via new since we are using smart pointers.
Parameters:
maxVelocity the maximum velocity for objects in the environment in m/s (used for computing doppler).
k a Ricean parameter.
Definition at line 212 of file fading.hpp.
References Ricean().
double Ricean::fadingFactor (const WirelessCommSignal & signal, const NodeId & nodeId) [virtual]
Compute the fading factor for the signal.
Parameters:
signal the signal being transmitted.
nodeId the ID of the receiver for which fading is being calculated.
Returns: the fading factor.
Implements Fading p..
Definition at line 65 of file fading.cpp.
References Simulator::currentTime(), Simulator::getRandNumGenerator(), SimTime::getTimeInSeconds(), WirelessCommSignal::getWavelength(), Simulator::instance(), and Fading::m_nodeOffset.
The documentation for this class was generated from the following files:
fading.hpp
fading.cpp