Signal Class Reference
A signal that can be transmitted over a channel.
#include <signal.hpp>
Public Types
typedef boost::shared_ptr< Signal > SignalPtr
Smart pointer that clients should use.
Public Member Functions
virtual ~Signal ()
A destructor.
Location getLocation () const
Get the geographic location of the signal source.
double getDbStrength () const
Get the strength in decibels of this signal.
Static Public Member Functions
static SignalPtr create (const Location &location, double dbStrength)
A factory method to ensure that all objects are created via new since we are using smart pointers.
static SignalPtr create (const Signal &rhs)
A factory method to ensure that all objects are created via new since we are using smart pointers.
Protected Member Functions
Signal (const Location &location, double dbStrength)
A constructor.
Signal (const Signal &rhs)
A copy constructor.
virtual SignalPtr clone () const
Returns a pointer to a deep copy of this object.
Friends
ostream & operator<< (ostream &s, const Signal &rhs)
ostream & operator<< (ostream &s, const WirelessCommSignal &rhs)
Detailed Description
A signal that can be transmitted over a channel.
Definition at line 17 of file signal.hpp.
Member Function Documentation
SignalPtr Signal::clone () const [protected, virtual]
Returns a pointer to a deep copy of this object.
This is addresses the slicing problem with copy construction.
Returns: a pointer to a deep copy of this object.
Reimplemented in WirelessCommSignal p..
Definition at line 21 of file signal.cpp.
References Signal().
Referenced by create().
double Signal::getDbStrength () const [inline]
Get the strength in decibels of this signal.
Returns: the strength in decibels.
Definition at line 105 of file signal.hpp.
Referenced by TwoRay::getRecvdStrength(), and FreeSpace::getRecvdStrength().
Location Signal::getLocation () const [inline]
Get the geographic location of the signal source.
Returns: a pointer to the location object.
Definition at line 100 of file signal.hpp.
Referenced by TwoRay::getRecvdStrength(), and FreeSpace::getRecvdStrength().
The documentation for this class was generated from the following files:
signal.hpp
signal.cpp