NodeId Class Reference
The node ID class provides a representation of the node's identifier.
#include <node.hpp>
Public Member Functions
NodeId (t_uint numericValue)
A constructor.
NodeId (const t_uchar *byteArray, t_uint byteCount)
A constructor.
virtual ~NodeId ()
A destructor.
void writeToByteArray (t_uchar *byteArray, t_uint byteCount) const
Write the NodeId's numeric value to the given byte array.
virtual string getStringValue () const
Get a string representation of the ID.
virtual t_uint getNumericValue () const
Get a numeric representation of the ID.
bool operator== (const NodeId &rhs) const
Compare two IDs for equality.
bool operator< (const NodeId &rhs) const
Compare two IDs for inequality.
Static Public Member Functions
static t_uint broadcastDestination ()
Return the value that indicates the broadcast destination.
Protected Attributes
t_uint m_numericValue
The internal representation of the ID.
Detailed Description
The node ID class provides a representation of the node's identifier.
Definition at line 27 of file node.hpp.
Constructor & Destructor Documentation
NodeId::NodeId (t_uint numericValue) [inline]
A constructor.
Parameters:
numericValue the numeric value for the node's ID.
Definition at line 39 of file node.hpp.
NodeId::NodeId (const t_uchar * byteArray, t_uint byteCount) [inline]
A constructor.
Parameters:
byteArray a pointer to the first element of the byte array with which to construct the NodeId. The zero-th element is the least significant byte.
byteCount the number of bytes in the array.
Definition at line 51 of file node.hpp.
References m_numericValue.
Member Function Documentation
static t_uint NodeId::broadcastDestination () [inline, static]
Return the value that indicates the broadcast destination.
Returns: the address of the broadcast destination.
Definition at line 91 of file node.hpp.
Referenced by RfidReaderMac::createRequestPacket(), getStringValue(), RfidTagMac::handleRecvdMacPacket(), RfidReaderMac::handleRecvdUpperLayerPacket(), RfidTagMac::packetIsForMe(), and RfidReaderMac::packetIsForMe().
virtual t_uint NodeId::getNumericValue () const [inline, virtual]
Get a numeric representation of the ID.
Returns: the numeric representation.
Definition at line 114 of file node.hpp.
References m_numericValue.
Referenced by writeToByteArray().
virtual string NodeId::getStringValue () const [inline, virtual]
Get a string representation of the ID.
Returns: the string representation.
Definition at line 100 of file node.hpp.
References broadcastDestination(), and m_numericValue.
bool NodeId::operator< (const NodeId & rhs) const [inline]
Compare two IDs for inequality.
Returns: true if the left hand ID is less than the right hand ID.
Definition at line 133 of file node.hpp.
References m_numericValue.
bool NodeId::operator== (const NodeId & rhs) const [inline]
Compare two IDs for equality.
Returns: true if they are equal.
Definition at line 123 of file node.hpp.
References m_numericValue.
void NodeId::writeToByteArray (t_uchar * byteArray, t_uint byteCount) const [inline]
Write the NodeId's numeric value to the given byte array.
Parameters:
byteArray a pointer to the first element of the byte array to be written. The zero-th byte will be the least signficant byte.
byteCount the number of bytes in the array.
Definition at line 71 of file node.hpp.
References getNumericValue().
Referenced by RfidReaderAppData::setReaderId(), RfidTagMacData::setReceiverId(), RfidReaderMacData::setReceiverId(), RfidTagMacData::setSenderId(), RfidReaderMacData::setSenderId(), and RfidTagAppData::setTagId().
Member Data Documentation
t_uint NodeId::m_numericValue [protected]
The internal representation of the ID.
See also: getNumericValue()
getStringValue()
Definition at line 143 of file node.hpp.
Referenced by getNumericValue(), getStringValue(), NodeId(), operator<(), and operator==().
The documentation for this class was generated from the following file:
node.hpp