TwoRay Class Reference
This computes the received signal strength using the TwoRay Ground Refelection model at longer distances and FreeSpace for shorter distances.
#include <path_loss.hpp>
Public Types
typedef boost::shared_ptr< TwoRay > TwoRayPtr
Smart pointer that clients should use.
Public Member Functions
virtual double getRecvdStrength (const WirelessCommSignal &signal, const PhysicalLayer &receiver) const
Compute the signal strength for the signal at the receiver.
Static Public Member Functions
static TwoRayPtr create ()
A factory method to ensure that all objects are created via new since we are using smart pointers.
static TwoRayPtr create (double lossFactor)
A factory method to ensure that all objects are created via new since we are using smart pointers.
Protected Member Functions
TwoRay ()
A constructor.
TwoRay (double lossFactor)
A constructor.
Detailed Description
This computes the received signal strength using the TwoRay Ground Refelection model at longer distances and FreeSpace for shorter distances.
The equation for the Two-Ray model is given by:
 P_r = \frac{P_t G_t G_r H_t H_r}{d^4 L} 
 where $P_r$ is the receiver power, $P_t$ is the transmitted power, $G_t$ and $G_r$ are the gains of the transmitter and receiver antennas, respectively, $H_t$ and $H_r$ is the transmitter and receiver antenna heights, $d$ is the distance between the transmitter and receiver, and $L$ is the loss factor. By default, $H_t = H_r = 0.0$.
Definition at line 126 of file path_loss.hpp.
Constructor & Destructor Documentation
TwoRay::TwoRay (double lossFactor) [protected]
A constructor.
Parameters:
lossFactor the loss factor of the model (must be >= 1).
Definition at line 40 of file path_loss.cpp.
Member Function Documentation
TwoRayPtr TwoRay::create (double lossFactor) [inline, static]
A factory method to ensure that all objects are created via new since we are using smart pointers.
Parameters:
lossFactor the loss factor of the model (must be >= 1).
Reimplemented from FreeSpace p..
Definition at line 196 of file path_loss.hpp.
References TwoRay().
double TwoRay::getRecvdStrength (const WirelessCommSignal & signal, const PhysicalLayer & receiver) const [virtual]
Compute the signal strength for the signal at the receiver.
Parameters:
signal the signal being transmitted.
receiver the object receiving the signal.
Returns: the signal strength in Watts.
Reimplemented from FreeSpace p..
Definition at line 62 of file path_loss.cpp.
References decibelsToPower(), Location::distance(), Signal::getDbStrength(), PhysicalLayer::getGain(), PhysicalLayer::getLocation(), Signal::getLocation(), FreeSpace::getRecvdStrength(), WirelessCommSignal::getTransmitterGain(), WirelessCommSignal::getWavelength(), LogStreamManager::instance(), LogStreamManager::logDebugItem(), PathLoss::m_DEBUG_SIGNAL_STRENGTH, FreeSpace::m_lossFactor, and PI.
The documentation for this class was generated from the following files:
path_loss.hpp
path_loss.cpp