RfidReaderPhy Class Reference
The physical layer class for a RFID reader.
#include <rfid_reader_phy.hpp>
Public Types
typedef boost::shared_ptr< RfidReaderPhy > RfidReaderPhyPtr
Smart pointer that clients should use.
Public Member Functions
virtual ~RfidReaderPhy ()
A destructor A virtual destructor is recommended since the class has virtual functions.
RfidReaderPhyPtr thisRfidReaderPhy ()
Gives this pointer as a RfidReaderPhy object.
PhysicalLayerPtr thisPhysicalLayer ()
Gives this pointer as a PhysicalLayer object.
SimulationEndListenerPtr thisSimulationEndListener ()
Gives this pointer as a SimulationEndListener object.
virtual void simulationEndHandler ()
The function called when the simulation ends.
bool setRegularChannel (t_uint channelId)
Set the listening channel for the RFID reader.
void resetRegularChannel ()
Invalidate the current listening channel.
bool setAllSendersChannel (t_uint channelId)
Set the channel on which this (and, presumably, all) readers are transmitting on.
void resetAllSendersChannel ()
Invalidate the current all senders channel.
Static Public Member Functions
static RfidReaderPhyPtr create (NodePtr node, WirelessChannelManagerPtr wirelessChannelManager)
A factory method to ensure that all objects are created via new since we are using smart pointers.
Protected Member Functions
RfidReaderPhy (NodePtr node, WirelessChannelManagerPtr wirelessChannelManager)
A constructor.
Detailed Description
The physical layer class for a RFID reader.
Definition at line 14 of file rfid_reader_phy.hpp.
Member Function Documentation
void RfidReaderPhy::resetAllSendersChannel ()
Invalidate the current all senders channel.
After calling this function, the reader is no longer sending to any channels.
See also: setAllSendersChannel()
setRegularChannel()
Definition at line 90 of file rfid_reader_phy.cpp.
References PhysicalLayer::m_wirelessChannelManagerPtr, and thisPhysicalLayer().
Referenced by setAllSendersChannel().
void RfidReaderPhy::resetRegularChannel ()
Invalidate the current listening channel.
After calling this function, the reader is no longer listening to any channels.
See also: setRegularChannel()
setAllSendersChannel()
Definition at line 40 of file rfid_reader_phy.cpp.
References PhysicalLayer::m_wirelessChannelManagerPtr, and thisPhysicalLayer().
Referenced by setRegularChannel().
bool RfidReaderPhy::setAllSendersChannel (t_uint channelId)
Set the channel on which this (and, presumably, all) readers are transmitting on.
All readers should be set to transmit on this channel, though they will listen on a different channel where not necessarily all readers are listening.
Parameters:
channelId the ID of the channel on which the readers will transmit.
Returns: true if the object is attached to the channel successfully.
See also: setRegularChannel()
resetAllSendersChannel()
Definition at line 73 of file rfid_reader_phy.cpp.
References PhysicalLayer::m_wirelessChannelManagerPtr, resetAllSendersChannel(), and thisPhysicalLayer().
bool RfidReaderPhy::setRegularChannel (t_uint channelId)
Set the listening channel for the RFID reader.
This corresponds to setting the channel on which the reader is listening since we model the reader's transmission channel as being on which all readers send on and all tags listen on.
Parameters:
channelId the ID of the channel on which the RFID reader will listen.
Returns: true if the object is attached to the channel successfully.
See also: setAllSendersChannel()
resetRegularChannel()
Definition at line 53 of file rfid_reader_phy.cpp.
References PhysicalLayer::m_wirelessChannelManagerPtr, resetRegularChannel(), and thisPhysicalLayer().
PhysicalLayerPtr RfidReaderPhy::thisPhysicalLayer () [inline, virtual]
Gives this pointer as a PhysicalLayer object.
This is used to deal with shared_ptr's, this, and inheritance.
Returns: a pointer to this object.
Implements PhysicalLayer p..
Definition at line 170 of file rfid_reader_phy.hpp.
Referenced by resetAllSendersChannel(), resetRegularChannel(), setAllSendersChannel(), setRegularChannel(), and ~RfidReaderPhy().
RfidReaderPhyPtr RfidReaderPhy::thisRfidReaderPhy () [inline]
Gives this pointer as a RfidReaderPhy object.
This is used to deal with shared_ptr's, this, and inheritance.
Returns: a pointer to this object.
Definition at line 164 of file rfid_reader_phy.hpp.
SimulationEndListenerPtr RfidReaderPhy::thisSimulationEndListener () [inline, virtual]
Gives this pointer as a SimulationEndListener object.
This is used to deal with shared_ptr's, this, and inheritance.
Returns: a pointer to this object.
Implements CommunicationLayer p..
Definition at line 176 of file rfid_reader_phy.hpp.
The documentation for this class was generated from the following files:
rfid_reader_phy.hpp
rfid_reader_phy.cpp