Node Class Reference
The class for a node in our system, which consists of a stack of CommunicationLayer objects connected together.
#include <node.hpp>
Public Types
typedef boost::shared_ptr< Node > NodePtr
Smart pointer that clients should use.
Public Member Functions
virtual ~Node ()
A destructor.
Location getLocation () const
Get a copy of the location of this node.
NodeId getNodeId () const
Get a copy of the ID of this node.
SimTime currentTime () const
Get the current time at the node.
bool scheduleEvent (EventPtr eventToSchedule, const SimTime &eventDelay)
Add an event to the simulator's event queue.
bool cancelEvent (EventPtr eventToCancel)
Cancel an event from the event queue.
Static Public Member Functions
static NodePtr create (const Location &location, const NodeId &nodeId)
A factory method to ensure that all objects are created via new since we are using smart pointers.
Protected Member Functions
Node (const Location &location, const NodeId &nodeId)
A constructor.
Detailed Description
The class for a node in our system, which consists of a stack of CommunicationLayer objects connected together.
Eventually, this could contain things like an energy consumption tracker and sensors as well.
Definition at line 153 of file node.hpp.
Constructor & Destructor Documentation
Node::Node (const Location & location, const NodeId & nodeId) [protected]
A constructor.
Parameters:
location the location object for this node.
nodeId the ID for this node.
Definition at line 5 of file node.cpp.
Referenced by create().
Member Function Documentation
bool Node::cancelEvent (EventPtr eventToCancel)
Cancel an event from the event queue.
Parameters:
eventToCancel a pointer to the event being cancelled.
Returns: true if the event was found and erased.
See also: scheduleEvent()
Definition at line 46 of file node.cpp.
References Simulator::cancelEvent(), and Simulator::instance().
NodePtr Node::create (const Location & location, const NodeId & nodeId) [inline, static]
A factory method to ensure that all objects are created via new since we are using smart pointers.
Parameters:
location the location object for this node.
nodeId the ID of this node.
Definition at line 238 of file node.hpp.
References Node().
SimTime Node::currentTime () const
Get the current time at the node.
Note that this may incorporate clock drift to be different that the simulator's currentTime().
Returns: The current time at the node.
Definition at line 32 of file node.cpp.
References Simulator::currentTime(), and Simulator::instance().
Location Node::getLocation () const [inline]
Get a copy of the location of this node.
Returns: a copy of the location of this node.
Definition at line 245 of file node.hpp.
NodeId Node::getNodeId () const [inline]
Get a copy of the ID of this node.
Returns: a copy of the ID of this node.
Definition at line 250 of file node.hpp.
bool Node::scheduleEvent (EventPtr eventToSchedule, const SimTime & eventDelay)
Add an event to the simulator's event queue.
Parameters:
eventToSchedule a pointer to the event being scheduled.
eventDelay how far in the future (from the node's local time) the event should be scheduled.
Returns: true if the event was successfully scheduled.
See also: cancelEvent()
Definition at line 39 of file node.cpp.
References Simulator::instance(), and Simulator::scheduleEvent().
The documentation for this class was generated from the following files:
node.hpp
node.cpp