FreeSpace Class Reference
This computes the received signal strength using the Friis free space model.
#include <path_loss.hpp>
Public Types
typedef boost::shared_ptr< FreeSpace > FreeSpacePtr
Smart pointer that clients should use.
Public Member Functions
virtual double getRecvdStrength (const WirelessCommSignal &signal, const PhysicalLayer &receiver) const
Compute the signal strength for the signal at the receiver.
Static Public Member Functions
static FreeSpacePtr create ()
A factory method to ensure that all objects are created via new since we are using smart pointers.
static FreeSpacePtr create (double lossFactor)
A factory method to ensure that all objects are created via new since we are using smart pointers.
Protected Member Functions
FreeSpace ()
A constructor.
FreeSpace (double lossFactor)
A constructor.
Protected Attributes
double m_lossFactor
The multiplier for how much signal loss a signal experiences.
Static Protected Attributes
static const double m_DEFAULT_LOSS_FACTOR = 1.0
The default loss factor.
Detailed Description
This computes the received signal strength using the Friis free space model.
The equation for the model * is given by:
 P_r = \frac{P_t G_t G_r \lambda^2}{(4\pi)^2 d^2 L} 
 where $P_r$ is the receiver power, $P_t$ is the transmitted power, $G_t$ and $G_r$ are the gains of the transmitter and receiver antennas, respectively, $\lambda$ is the wavelength, $d$ is the distance between the transmitter and receiver, and $L$ is the loss factor.
Definition at line 59 of file path_loss.hpp.
Constructor & Destructor Documentation
FreeSpace::FreeSpace (double lossFactor) [protected]
A constructor.
Parameters:
lossFactor the loss factor of the model (must be >= 1).
Definition at line 26 of file path_loss.cpp.
References m_DEFAULT_LOSS_FACTOR, and m_lossFactor.
Member Function Documentation
FreeSpacePtr FreeSpace::create (double lossFactor) [inline, static]
A factory method to ensure that all objects are created via new since we are using smart pointers.
Parameters:
lossFactor the loss factor of the model (must be >= 1).
Reimplemented in TwoRay p..
Definition at line 184 of file path_loss.hpp.
References FreeSpace().
double FreeSpace::getRecvdStrength (const WirelessCommSignal & signal, const PhysicalLayer & receiver) const [virtual]
Compute the signal strength for the signal at the receiver.
Parameters:
signal the signal being transmitted.
receiver the object receiving the signal.
Returns: the signal strength in Watts.
Implements PathLoss p..
Reimplemented in TwoRay p..
Definition at line 46 of file path_loss.cpp.
References decibelsToPower(), Location::distance(), Signal::getDbStrength(), PhysicalLayer::getGain(), PhysicalLayer::getLocation(), Signal::getLocation(), WirelessCommSignal::getTransmitterGain(), WirelessCommSignal::getWavelength(), m_lossFactor, and PI.
Referenced by TwoRay::getRecvdStrength().
The documentation for this class was generated from the following files:
path_loss.hpp
path_loss.cpp