Packet Class Reference
Defines a representation of the packets that are exchanged between nodes.
#include <packet.hpp>
Public Types
typedef boost::shared_ptr< Packet > PacketPtr
Smart pointer that clients should use.
typedef map< DataTypes, PacketDataPtr > DataTypeMap
Map of a packet pointer for each of the network stack layers.
DataTypes_Physical
enum value DataTypes_Physical.
DataTypes_Link
enum value DataTypes_Link.
DataTypes_Network
enum value DataTypes_Network.
DataTypes_Transport
enum value DataTypes_Transport.
DataTypes_Application
enum value DataTypes_Application.
enum DataTypes {
DataTypes_Physical,
DataTypes_Link,
DataTypes_Network,
DataTypes_Transport,
DataTypes_Application
 }
DataTypes enum.
Public Member Functions
virtual ~Packet ()
A destructor.
t_uint getSizeInBytes () const
Returns the packet size.
t_uint getSizeInBits () const
Returns the packet size.
double getDataRate () const
Get the data rate at which the packet is sent.
void setDataRate (double dataRate)
Set the data rate at which the packet is sent.
bool getHasError () const
Get whether or not the packet has an error.
void setHasError (bool hasError)
Set whether or not the packet has an error.
SimTime getDuration () const
Get the time duration of the packet.
void addData (DataTypes dataType, const PacketData &data)
Add a copy of the packet data to the packet as the specified type of data.
PacketDataPtr getData (DataTypes dataType)
Get a pointer to the data of the specified type stored in this packet.
bool removeData (DataTypes dataTypes)
Remove the data stored in the packet associated with the specified type.
bool hasUpperLayerData (DataTypes dataTypes)
Check if the packet has any data intended for upper layers.
void setDestination (const NodeId &destination)
Set the destination field of the packet.
NodeId getDestination () const
Get the destination field of the packet.
void setTxPower (double txPower)
Set the transmit power of the packet.
double getTxPower () const
Get the transmit power of the packet.
void setDoMaxTxPower (bool doMaxTxPower)
Set whether the packet should be transmitted at the maximum power available.
bool getDoMaxTxPower () const
Get whether the packet should be transmitted at the maximum power available.
t_ulong getUniqueId () const
Return the unique ID of this packet (used for debugging traces).
Static Public Member Functions
static PacketPtr create ()
A factory method to ensure that all objects are created via new since we are using smart pointers.
static PacketPtr create (const Packet &rhs)
A factory method to ensure that all objects are created via new since we are using smart pointers.
Protected Member Functions
Packet ()
A constructor.
Packet (const Packet &rhs)
A copy constructor.
virtual PacketPtr clone () const
Returns a pointer to a deep copy of this object.
Friends
ostream & operator<< (ostream &s, const Packet &packet)
Detailed Description
Defines a representation of the packets that are exchanged between nodes.
Definition at line 97 of file packet.hpp.
Member Enumeration Documentation
enum Packet::DataTypes
DataTypes enum.
The different data types that a packet may hold.
Enumerator:
DataTypes_Physical
 enum value DataTypes_Physical.
DataTypes_Link
 enum value DataTypes_Link.
DataTypes_Network
 enum value DataTypes_Network.
DataTypes_Transport
 enum value DataTypes_Transport.
DataTypes_Application
 enum value DataTypes_Application.
Definition at line 107 of file packet.hpp.
Member Function Documentation
void Packet::addData (DataTypes dataType, const PacketData & data)
Add a copy of the packet data to the packet as the specified type of data.
Parameters:
dataType the type of the data within the packet.
data the packet data; a deep copy of the data will be stored in the packet.
See also: getData()
removeData()
Definition at line 43 of file packet.cpp.
References PacketData::create().
PacketPtr Packet::clone () const [protected, virtual]
Returns a pointer to a deep copy of this object.
This is addresses the slicing problem with copy construction.
Returns: a pointer to a deep copy of this object.
Definition at line 37 of file packet.cpp.
References Packet().
Referenced by create().
PacketDataPtr Packet::getData (DataTypes dataType)
Get a pointer to the data of the specified type stored in this packet.
Parameters:
dataType the type of the data within the packet.
Returns: a pointer to the data of dataType or an empty pointer if no data is stored for that dataType.
Definition at line 49 of file packet.cpp.
Referenced by hasUpperLayerData().
double Packet::getDataRate () const [inline]
Get the data rate at which the packet is sent.
Returns: the data rate in bps.
See also: setDataRate()
Definition at line 430 of file packet.hpp.
Referenced by getDuration().
NodeId Packet::getDestination () const [inline]
Get the destination field of the packet.
This is used by lower layers that are unaware of the data format of upper layers and does not count towards the size of the packet.
Returns: the desintation.
Definition at line 456 of file packet.hpp.
bool Packet::getDoMaxTxPower () const [inline]
Get whether the packet should be transmitted at the maximum power available.
If this is set to true, then the value of getTxPower() is ignored.
Returns: true if the packet should be transmitted at the maximum power level.
See also: setDoMaxTxPower()
setTxPower()
getTxPower()
Definition at line 477 of file packet.hpp.
SimTime Packet::getDuration () const
Get the time duration of the packet.
Returns: the time duration of the packet.
Definition at line 109 of file packet.cpp.
References getDataRate(), and getSizeInBits().
bool Packet::getHasError () const [inline]
Get whether or not the packet has an error.
Returns: true if the packet has an error.
See also: setHasError()
Definition at line 441 of file packet.hpp.
t_uint Packet::getSizeInBits () const [inline]
Returns the packet size.
Returns: the number of bits in the packet.
See also: getSizeInBytes()
Definition at line 425 of file packet.hpp.
References getSizeInBytes().
Referenced by getDuration().
t_uint Packet::getSizeInBytes () const [inline]
Returns the packet size.
Returns: the number of bytes in the packet.
See also: getSizeInBites()
Definition at line 406 of file packet.hpp.
Referenced by getSizeInBits().
double Packet::getTxPower () const [inline]
Get the transmit power of the packet.
If this is set to zero, then the current power level will be used. The value must be greater than or equal to zero. This is superseded if getDoMaxTxPower() is true. In this case, the packet will be transmitted at the physical layer's maximum power regardless of the input to this function.
Returns: the transmit power to use or zero if the current power level should be used.
See also: setTxPower()
setDoMaxTxPower()
getDoMaxTxPower()
Definition at line 467 of file packet.hpp.
t_ulong Packet::getUniqueId () const [inline]
Return the unique ID of this packet (used for debugging traces).
Returns: the unique ID of the packet.
Definition at line 482 of file packet.hpp.
bool Packet::hasUpperLayerData (DataTypes dataTypes)
Check if the packet has any data intended for upper layers.
Parameters:
dataTypes the type of data for the layer being checked.
Returns: true if there is any data in the packet for layers above the once being checked.
Definition at line 70 of file packet.cpp.
References DataTypes_Application, DataTypes_Link, DataTypes_Network, DataTypes_Physical, DataTypes_Transport, and getData().
bool Packet::removeData (DataTypes dataTypes)
Remove the data stored in the packet associated with the specified type.
Parameters:
dataTypes the type of the data within the packet.
Returns: true if the data of dataTypes was successfully removed.
Definition at line 63 of file packet.cpp.
void Packet::setDataRate (double dataRate) [inline]
Set the data rate at which the packet is sent.
Returns: the data rate in bps.
See also: getDataRate()
Definition at line 435 of file packet.hpp.
void Packet::setDestination (const NodeId & destination) [inline]
Set the destination field of the packet.
This is used by lower layers that are unaware of the data format of upper layers and does not count towards the size of the packet.
Parameters:
destination the desintation.
Definition at line 451 of file packet.hpp.
void Packet::setDoMaxTxPower (bool doMaxTxPower) [inline]
Set whether the packet should be transmitted at the maximum power available.
If this is set to true, then the value of getTxPower() is ignored.
Parameters:
doMaxTxPower set to true if the packet should be transmitted at the maximum power level.
See also: getDoMaxTxPower()
setTxPower()
getTxPower()
Definition at line 472 of file packet.hpp.
void Packet::setHasError (bool hasError) [inline]
Set whether or not the packet has an error.
Parameters:
hasError set to true if the packet has an error.
See also: getHasError()
Definition at line 446 of file packet.hpp.
void Packet::setTxPower (double txPower) [inline]
Set the transmit power of the packet.
If this is set to zero, then the current power level will be used. The value must be greater than or equal to zero. This is superseded if getDoMaxTxPower() is true. In this case, the packet will be transmitted at the physical layer's maximum power regardless of the input to this function.
Parameters:
txPower the transmit power to use or zero if the current power level should be used.
See also: getTxPower()
setDoMaxTxPower()
getDoMaxTxPower()
Definition at line 461 of file packet.hpp.
The documentation for this class was generated from the following files:
packet.hpp
packet.cpp